### ISSUE TITLE
Incongruencia no simulado do problema

### ISSUE THREAD

**Issue by Bbeluco** [bankme-tech/aprove-me#33]
Boa noite!

Estou tentando desenvolvedor um projeto baseado nos requisitos do teste tecnico (nao estou concorrendo a vaga, apenas estudando) e durante a criacao notei que ha um ponto meio confuso com os titulos da tabela do banco.

Na parte "_Estrutura de um recebível_" temos uma tabela com alguns campos que o DB deve ter. A tabela atual seria a seguinte:

### Estrutura de um recebível

| CAMPO        | TIPO          | DESCRIÇÃO                                 |
|--------------|---------------|-------------------------------------------|
| id           | string (UUID) | É a identificação de um recebível.        |
| value        | float         | É o valor do recebível.                   |
| emissionDate | date          | É a data de emissão do recebível.         |
| assignor     | int           | Representa a identificação de um cedente. |

Se notarmos bem, a ultima linha se trata de um **identificador** de um cedente que eh de tipo **INT**
Porem, na parte de backend, no nivel 1 eh descrito o seguinte na parte de validacoes da API:

2. **Os ids devem ser do tipo UUID**

Tendo em vista essa afirmacao, o assignor nao deveria ser do tipo "string (UUID)" assim como o "id" da tabela de estrutura de um recebivel?

OBS: Desculpem a falta de acentuacao, meu teclado nao possui acentos

**Comment by diogocezar** [comment]
Valeus demais mestre, ajustando aqui ;)

**Comment by diogocezar** [comment]
Ajustado ;)
