### ISSUE TITLE
Dúvida sobre Implementação do Sistema de Autenticação

### ISSUE THREAD

**Issue by deivisonisidoro** [bankme-tech/aprove-me#37]
Olá, td bem? Fiquei com uma dúvida relacionada ao sistema de autenticação. Na descrição do teste, percebi que foram mencionadas duas entidades: "recebível" e "cedente". No entanto, no nível 4 onde a funcionalidade de autenticação é descrita não está claro sobre qual entidade devemos implementá-la.

Minha dúvida é: devo implementar o sistema de login na entidade "cedente", e com isso adicionar mais dois campos a ela (login e password)? Ou devo criar uma nova entidade chamada "User" que conterá os campos "login" e "password"?

Agradeço desde já pela ajuda!

**Comment by Thiago-F** [comment]
Olá @deivisonisidoro, sim, o cedente será o user da aplicação, então imagine que ele que terá que colocar o email e senha para se autenticar. A maneira que você ira armazenar essa informação fica a seu critério.

**Comment by dalloglio** [comment]
O usuário que faz o login na plataforma seria o cliente que solicitou a nova funcionalidade? Dessa forma, ele poderia fazer login na plataforma e ter a permissão de apenas gerenciar os seus próprios recebíveis e cedentes, não tendo a permissão de gerenciar recebíveis e cedentes de outros clientes? Ou cada cedente é um cliente, e também, só tem permissão de gerenciar registros atrelados a ele?

Outra dúvida que fiquei é? Vai ser o time de operações ou o próprio cliente que vai cadastrar os recebíveis? Se for o time de operações, não faz sentido o cliente ou o cedente conforme citei acima ser o usuário e sim a pessoa de operação.
