### ISSUE TITLE
Banco de Dados SQLite

### ISSUE THREAD

**Issue by lamenkazu** [bankme-tech/aprove-me#40]
É uma obrigação que o banco de dados seja SQLite?
Fazer testes com o banco Postgresql por exemplo seria muito mais fácil. Estou tendo problemas pra limpar o banco de testes a cada teste para manter uma unidade entre eles. Posso pesquisar mais um pouco sobre isso, mas creio que com SQLite não seja tão funcional fazer isso.

Além disso gostaria de saber sobre se há algum prazo pra entrega do projeto.

**Comment by yazaldefilimone** [comment]
hei, @lamenkazu.

tentou colocar deletacao em cascada na referencia da outra tabela?
```prisma

assignor     Assignor @relation(fields: [assignorId], references: [id], onDelete: Cascade)

```


e nos seus testes nesse ordem: 
```ts
  afterAll(async () => {
    await prisma.receivable.deleteMany(); // 1
    await prisma.assignor.deleteMany(); // 2

  });

```


quando tentei colocar em cada teste dava uns bugs de forgen key, nao sei o certo mas acho. que e por conta que esta rodando nos workers(or threads)... so achei isso, mas nao e uma certeza

**Comment by lamenkazu** [comment]
Olá, obrigado pela resposta, mas não é esse o meu problema.
O problema é que todos os testes ocorrem no mesmo banco de dados, e se fosse com PostgreSQL eu poderia criar um schema para cada teste. O código de deleteMany() não funciona muito bem mesmo que eu faça beforeEach() ou afterEach(), porque os testes são assincronos, então a cada vez que rodo todos os testes, se torna arbitrário a ordem em que eles executam e as vezes um teste roda antes que o código de deleteMany() seja completo.

Quando rodo cada teste E2E individualmente eles rodam muito bem respeitando os deletes que eu estipulei no meu setup-e2e.ts, mas a questão é quando rodo todos os testes juntos mesmo.

Como todos usam o mesmo arquivo de testes, acaba não funcionando muito bem. A questão é que eu sei que rodando individualmente todos os testes passam, e que está tudo ok, mas o problema é realmente esse de usar o mesmo arquivo para testes, o que não aconteceria em Postgre, por exemplo. Mas se é obrigatório a utilização do SQLite eu vou aceitar esse fato por enquanto.

Obrigado pelo tempo!

**Comment by yazaldefilimone** [comment]
> Olá, obrigado pela resposta, mas não é esse o meu problema. O problema é que todos os testes ocorrem no mesmo banco de dados, e se fosse com PostgreSQL eu poderia criar um schema para cada teste. O código de deleteMany() não funciona muito bem mesmo que eu faça beforeEach() ou afterEach(), porque os testes são assincronos, então a cada vez que rodo todos os testes, se torna arbitrário a ordem em que eles executam e as vezes um teste roda antes que o código de deleteMany() seja completo.
> 
> Quando rodo cada teste E2E individualmente eles rodam muito bem respeitando os deletes que eu estipulei no meu setup-e2e.ts, mas a questão é quando rodo todos os testes juntos mesmo.
> 
> Como todos usam o mesmo arquivo de testes, acaba não funcionando muito bem. A questão é que eu sei que rodando individualmente todos os testes passam, e que está tudo ok, mas o problema é realmente esse de usar o mesmo arquivo para testes, o que não aconteceria em Postgre, por exemplo. Mas se é obrigatório a utilização do SQLite eu vou aceitar esse fato por enquanto.
> 
> Obrigado pelo tempo!

Ham, interessante, nesse caso eu rodaria unit teste primeiro. depois e2e mas como quer rodar todos de uma unica vez pode tentar usar banco com memory mode, em cada tipo de teste de tiver(unit ou e2e...)  algo proximo de:

```ts

beforeAll(async () => {
  const moduleFixture: TestingModule = await Test.createTestingModule({
    imports: [seuModulo],
  }).compile();

  app = moduleFixture.createNestApplication();
  await app.init();

  prisma = new PrismaClient({
    datasources: {
      db: {
        url: 'file:./test.db?mode=memory&cache=shared',
      },
    },
  });

  await prisma.$connect();
});

```

mas com isso pode desativar as keys em cada teste, usando `PRAGMA foreign_keys=OFF` e deletar os dados depois voltar a ativar


pode ver mais. sobre em: https://www.sqlite.org/pragma.html 





mas com tudo, nao sei se e obrigatorio usar ou nao....
