### ISSUE TITLE
Prazo desafio técnico

### ISSUE THREAD

**Issue by elvesbd** [bankme-tech/aprove-me#69]
Gostaria de saber se ainda é possível enviar o desafio técnico. Existe uma data limite para o envio? Seria possível encaminhá-lo até o final desta semana?

Agradeço desde já pela atenção e fico no aguardo de uma resposta.

Elves Brito,

**Comment by Wellers0n** [comment]
Já fechamos as vagas, encontramos os desenvolvedores. Não tem prazo de envio
